import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ru' | 'kz';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('en');

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
  };

  const t = (key: string): string => {
    return translations[currentLanguage][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Meta
    'meta.title': 'Ritm Oil LLP - Oil Industry Services in Kazakhstan',
    'meta.description': 'Leading provider of hotel business, catering, transport and logistics services for the oil and gas industry in Kazakhstan',

    // Common
    'common.learn_more': 'Learn More',
    'common.contact_us': 'Contact Us',

    // Hero
    'hero.title': 'Welcome to Ritm Oil LLP',
    'hero.subtitle': 'Leading provider of comprehensive oil industry services across Kazakhstan',
    'home.hero.description': 'Providing comprehensive logistics, catering, and accommodation services to the oil and gas industry in Kazakhstan since 2004.',

    // Home page
    'home.about.title': 'About Ritm Oil LLP',
    'home.about.description_1': '"Ritm Oil” LLP has started its business activity in 2001 in oil trading, logistics services to the KPO b.v. contractors in Aksai city, west Kazakhstan region. We carried out technical maintenance service in KPO b.v. sites, including dismantling and disposal of some types of temporary buildings and constructions.',
    'home.about.description_2': 'At present the company is focused in Facility Management of NCOC, hotel services, catering, transport services and waste recycling for companies which are working in the oil and gas sector of the Republic of Kazakhstan.',
    'home.about.description_3': 'The company has hotel, Camps, Office in Atyrau and Almaty city. The Company`s core asset is the team of 300 employees. The key management staff of Ritm Oil has been working more than 15 years in the company.',
    'home.about.quote': '"Hospitality is our attitude"',
    'home.services.title': 'Our Services',
    'home.services.subtitle': 'Comprehensive solutions for the oil and gas industry',
    'home.services.hotel.title': 'Hotel Business',
    'home.services.hotel.description': 'Professional hotel management and accommodation services',
    'home.services.catering.title': 'Catering Services',
    'home.services.catering.description': 'Quality catering and camp management solutions',
    'home.services.transport.title': 'Transport & Logistics',
    'home.services.transport.description': 'Reliable transport and logistics services',
    'home.services.management.title': 'Management Services',
    'home.services.management.description': 'Professional management and consulting',
    'home.services.franchise.title': 'Franchise Services',
    'home.services.franchise.description': 'Brand affiliation and franchise support',
    'home.cta.title': 'Ready to Partner with Us?',
    'home.cta.subtitle': 'Contact us today to discuss your business needs',
    'home.cta.button': 'Get in Touch',

    // Header
    'header.main': 'Main',
    'header.about.title': 'About',
    'header.about.mission': 'Mission and Purposes',
    'header.about.history': "Company's History",
    'header.about.management': 'Management',
    'header.about.assets': 'Intangible Assets',
    'header.services.title': 'Services',
    'header.services.hotel': 'Hotel Business',
    'header.services.catering': 'Catering and Camp Management',
    'header.services.transport': 'Transport and Logistics',
    'header.services.management': 'Management Agreement',
    'header.services.franchise': 'Franchise Agreement',
    'header.clients': 'Clients',
    'header.contacts': 'Contacts',
    'img.logo' : '/src/img/logo_ritmoil_eng.png',
    
    // Footer
    'footer.description': 'Leading provider of comprehensive oil industry services including hotel business, catering, transport logistics, and management solutions.',
    'footer.contact.title': 'Contact Information',
    'footer.contact.main_office': 'Main Office',
    'footer.contact.general_inquiries': 'General Inquiries',
    'footer.contact.location': '1A, Druzhba, Atyrau, Kazakhstan',
    'footer.contact.head_office': 'Head Office',
    'footer.quick_links': 'Quick Links',
    'footer.links.mission': 'Mission',
    'footer.links.hotel': 'Hotel Business',
    'footer.links.history': 'History',
    'footer.links.catering': 'Catering',
    'footer.links.management': 'Management',
    'footer.links.transport': 'Transport',
    'footer.links.clients': 'Clients',
    'footer.links.contacts': 'Contacts',
    'footer.copyright': '© 2025 Ritm Oil LLP. All rights reserved.',

    // Mission page
    'mission.title': 'Mission and Purposes',
    'mission.subtitle': 'Our commitment to excellence in serving the oil and gas industry',
    'mission.our_mission': 'Our Mission : ',
    'mission.our_purposes': 'Our Purposes : ',
    'mission.statement': 'To provide the best services to our Clients on the basis of the international business standards',
    'mission.client_excellence': 'Client Excellence',
    'mission.client_excellence_desc': 'To exceed expectations of the Clients providing high-quality service.',
    'mission.employee_development': 'Employee Development',
    'mission.employee_development_desc': 'To become the attractive company for employee\'s development.',
    'mission.social_responsibility': 'Social Responsibility',
    'mission.social_responsibility_desc': 'To be socially responsible company.',
    'mission.business_growth': 'Business Growth',
    'mission.business_growth_desc': 'To increase business capitalization and the profit of founders.',
    'mission.iso.title': 'International Standards',
    'mission.iso.description': 'Management of Ritm Oil LLP conforms to the international ISO standard 22000:2005 which is verified by the certificate of N TFSMS/16/XX/AN dated 18.04.2016 issued by Italian auditing company "Rina Service SPA".',
    'mission.motto': 'In a same rhythm to the collective success!',

    // History page
    'history.title': 'Company\'s History',
    'history.subtitle': 'Over two decades of excellence in the oil and gas service industry',
    'history.journey.title': 'Our Journey',
    'history.journey.description': 'Ritm Oil LLP has been providing accommodation, meal and maintenance services for companies working in the oil and gas sector of the Republic of Kazakhstan for over 20 years. At the beginning of our business activity, Ritm Oil carried out technical maintenance services in KPO b.v. sites, including dismantling and disposal of various types of temporary buildings and constructions.',
    'history.milestones.title': 'Key Milestones',
    'history.milestones.2001': 'Company founded - Started business activity in oil trading and logistics services to KPO b.v. contractors in Aksai city',
    'history.milestones.2003': 'Constructed and put into operation Green Hotel in Atyrau city',
    'history.milestones.2005': 'Acquired Zhuldyz hotel in Aksay city, West Kazakhstan region',
    'history.milestones.2006': 'Constructed Tengri hotel in Atyrau city',
    'history.milestones.2007': 'Put into operation Tengri hotel for Tsesna corporation in Astana city under own trademark',
    'history.milestones.2009': 'Built the Ritm shift camp for Contractors staff of Agip KCO',
    'history.milestones.2013': 'Won the tender for catering and maintenance services for Agip KCO training center',
    'history.milestones.2015': 'Constructed and brought into operation Ramada hotel in Almaty city as franchise of American hotel network "Wyndham Worldwide"',
    'history.milestones.2016': 'Started providing Facility management services and catering services for NCOC NV',
    'history.today.title': 'Today',
    'history.today.properties.title': 'Multiple Properties',
    'history.today.properties.description': 'Hotels, camps, and offices across Kazakhstan',
    'history.today.locations.title': 'Strategic Locations',
    'history.today.locations.description': 'Operations in Atyrau, Almaty, and Aksai',
    'history.today.experience.title': '20+ Years',
    'history.today.experience.description': 'Of experience and continuous growth',
    
    // Management page
    'management.title': 'Management',
    'management.subtitle': 'Professional leadership driving our success',
    'management.philosophy.title': 'Our Leadership Philosophy',
    'management.philosophy.description1': 'As a quickly expanding company, we have always considered pacing our further steps on solid platforms. We believe that a business is valuable when its infrastructures are strong. We have dedicated a knowledgeable and creative team to recognize the everyday demands of markets and assist our operations in order to be up to date and innovative.',
    'management.philosophy.description2': 'Our successes are the result of the dedicated efforts of the Professional Team led by the following experienced professionals:',
    'management.team.chairman.name': 'Tatiyev Murat Petrovich',
    'management.team.chairman.position': 'Chairman of the Board',
    'management.team.chairman.description': 'Mr. Tatiyev M. has an academic background of two degrees, including economics in "Finance and Credit", with 30 years of experience in senior administrative jobs. Since the incorporation of the company, he has kept himself responsible for all strategic planning, organization and personnel administration.',
    'management.team.general_director.name': 'Saha Subhasis',
    'management.team.general_director.position': 'General Director',
    'management.team.general_director.description': 'Mr. Saha\'s experience in hospitality industry spans 25 years in different parts of India and Kazakhstan. In 2002, at the very early stage of incorporation of Ritmoil LLP, Mr. Saha joined the company as General Manager, overseeing the operations of all properties and playing a key role in the expansion and development of future hotels. He assumed the role as General Director & Co-founder of "Ritmoil LLP" in 2010. Mr. Saha had completed his higher education in Hotel Management from one of the most prestigious institutes in India - IHM, Bangalore.',
    'management.team.operations_manager.name': 'Roy Basab',
    'management.team.operations_manager.position': 'General Manager, Operations and Marketing',
    'management.team.operations_manager.description': 'Mr. Roy, PhD, has completed his Masters from Azerbaijan Institute. He has vast experience in CIS countries in the field of marketing and has been working in different parts of CIS. He has been associated with Ritm Oil LLP since 2010 and has been directly involved in developing the Company to different levels by direct association with major Oil companies and internationally acclaimed construction companies.',
    'management.team.hr_director.name': 'Yelizarova Olga Vladimirovna',
    'management.team.hr_director.position': 'Director of HR',
    'management.team.hr_director.description': 'Ms. Yelizarova O., with her academic qualifications in the field of economics and law, has been working in «RitmOil» from the foundation of the company as the HR director. She is responsible for the organization of Personnel and Administrative Jobs.',
    'management.team.finance_director.name': 'Gabdullin Nurlan Imangaziyevich',
    'management.team.finance_director.position': 'Director of Finance',
    'management.team.finance_director.description': 'Mr. Gabdullin N. is charged with the task of overseeing the Ritm Group\'s Finance, Mergers and Acquisitions, Purchase and Legal functions. With over 14 years of experience in the Ritm Group in various financial roles, he brings a unique understanding of fiscal responsibility to Ritmoil. He is also responsible for all negotiations with bankers and Government Financing Institution "DAMU". Mr. Gabdullin N. has a doctorate degree in economics.',
    'management.team.chief_accountant.name': 'Kalimukasheva Tamara Ermekovna',
    'management.team.chief_accountant.position': 'Chief Accountant',
    'management.team.chief_accountant.description': 'Ms. Kalimukasheva T.E. has been working as the chief accountant of the enterprise since 2003. Under her management, automated accounting and tax accounts based on the 1C platform have been introduced in the company. The creation of effective accounting policies has allowed for successful financial activity of the association.',
    'management.certifications.title': 'International Standards',
    'management.certifications.description': 'Ritm Oil Company management conforms to international standards which is verified by Certificates:',

    // Assets page
    'assets.title': 'Intangible Assets',
    'assets.subtitle': 'Our valuable licenses, certifications, and trusted partnerships',
    'assets.licenses.title': 'Licenses and Permits',
    'assets.licenses.description': 'Along with fixed assets "Ritm Oil" possesses all necessary licenses for the implementation of hotel business, quotas and permits for expats, registered in the Chamber of Commerce (CCI) a certificate of registration of trademark "Tengri".',
    'assets.licenses.business.title': 'Hotel Business Licenses',
    'assets.licenses.business.description': 'All necessary permits for hotel operations',
    'assets.licenses.trademark.title': 'Trademark Registrations',
    'assets.licenses.trademark.description': '"Tengri" trademark',
    'assets.insurance.title': 'Insurance Coverage',
    'assets.insurance.description': 'All of our real estates are covered by insurance policies of "Eurasia Insurance", the leader in the insurance market of Kazakhstan.',
    'assets.clients.title': 'Stable Client Portfolio',
    'assets.clients.description': 'One of the most important intangible assets is the presence of a stable, ever-increasing clientele, including the world\'s largest companies:',
    'assets.clients.list': 'NCOC, Parker Drilling, Saipem, Ersai, Sicim S.p.A., Wagenborg, FMC, Petroleum Facilities Е&C Limited, Weatherford, Baker Hughes, Bolashak Atyrau, Fircroft Engineering, Bonatti, Kaz Story Service, PSN KazStroy, Punj Lloyd, KCA-Deutag, Worley Parsons, Corporation JGС-Marubeni, ССС, Ligabue Central Asia, Bateman, Kentech',
    'assets.clients.footer': 'and many others.',
    'assets.financial.title': 'Financial Trust',
    'assets.financial.description': 'We are proud of the deserved trust of investors and banks that financed all of our projects and supported our dynamic development.',
    
    // Hotel page
    'hotel.title': 'Hotel Business',
    'hotel.subtitle': 'Premium accommodation services in the heart of Atyrau',
    'hotel.tengri.title': 'Tengri Hotel',
    'hotel.tengri.location': 'Located in downtown Atyrau',
    'hotel.tengri.description_1': 'The hotel is located in the downtown Atyrau. There are 60 rooms, 15 of them are apartments with kitchenette, 45 standard rooms. Each room is equipped with telecommunication and Internet connection, air conditioner and multi lingual satellite television system.',
    'hotel.tengri.description_2': 'Our guests especially enjoy the restaurant headed by the chefs from Italy and India. The bar available in hotel allows our customers to rest with colleagues and friends or hold a meeting. The lounge bar is equipped with wide screen projected system, where guests can enjoy different Sports Events.',
    'hotel.tengri.description_3': 'Additional attraction of the bar - the live music on Wednesdays and the Saturdays, organized by one of the most known musical groups of the city of Atyrau.',
    'hotel.amenities.rooms': '60 Rooms',
    'hotel.amenities.rooms_desc': '15 apartments with kitchenette, 45 standard rooms',
    'hotel.amenities.connectivity': 'Modern Connectivity',
    'hotel.amenities.connectivity_desc': 'Telecommunication and Internet connection in every room',
    'hotel.amenities.cuisine': 'Italian & Indian Cuisine',
    'hotel.amenities.cuisine_desc': 'Restaurant headed by chefs from Italy and India',
    'hotel.amenities.entertainment': 'Live Entertainment',
    'hotel.amenities.entertainment_desc': 'Live music on Wednesdays and Saturdays',
    'hotel.booking.title': 'Book Your Stay',
    'hotel.booking.description': 'Experience comfort and hospitality at Tengri Hotel',
    'hotel.booking.button': 'Book Now',
    
    // Catering page
    'catering.title': 'Catering and Camp Management',
    'catering.subtitle': 'Comprehensive food services and camp management solutions',
    'catering.services.title': 'Our Catering Services',
    'catering.services.subtitle': 'Providing exceptional food services and camp management across Kazakhstan',
    'catering.description_1': 'Besides managing the "Ritm Camp" and "Punj Lloyd", we had provided total camp management including catering, maintenance and housekeeping for "Consolidate Contractors Company" (CCC) for 1800 people per day till 2011.',
    'catering.description_2': 'High standard of food service helped us to win the tender in 2013 by Agip KCO for provision of catering and Cleaning Services in "Agip Training Center" in Atyrau.',
    'catering.description_3': 'We do organize and provide outdoor catering services in any special events of any clients.',
    'catering.services.camp_management': 'Camp Management',
    'catering.services.camp_management_desc': 'Total camp management including catering, maintenance and housekeeping services',
    'catering.services.high_capacity': 'High Capacity',
    'catering.services.high_capacity_desc': 'Provided services for up to 1800 people per day at various locations',
    'catering.services.quality_food': 'Quality Food Service',
    'catering.services.quality_food_desc': 'High standard of food service that helped us win major tenders',
    'catering.services.event_catering': 'Event Catering',
    'catering.services.event_catering_desc': 'Organize and provide outdoor catering services for special events',
    'catering.achievements.title': 'Key Achievements',
    'catering.achievements.people_served': 'People served per day',
    'catering.achievements.agip_tender': 'Won Agip KCO tender',
    'catering.achievements.years_experience': 'Years of experience',
    
    //transport page
    'transport.title': 'Transport and Logistics',
    'transport.subtitle': 'Comprehensive logistics solutions for the oil and gas industry',
    'transport.services.title': 'Transport and Logistics Services',
    'transport.services.subtitle': 'Modern logistics solutions designed for today\'s demanding market',
    'transport.full_range': 'Full Range Logistics',
    'transport.full_range_desc': 'Complete logistics services to manage cargo flows and supply chain management',
    'transport.just_in_time': 'Just-in-Time Delivery',
    'transport.just_in_time_desc': 'Efficient delivery schedules to match consumer demand and production needs',
    'transport.packing_moving': 'Packing & Moving',
    'transport.packing_moving_desc': 'Professional packing and moving services for household and corporate goods',
    'transport.city_transport': 'City & Intercity Transport',
    'transport.city_transport_desc': 'Reliable transportation services within cities and across regions',
    'transport.main_content.overview': 'Ritm Oil LLP provides comprehensive logistics services for managing cargo flows and supply chain operations, specializing in the oil and gas industry.',
    'transport.main_content.supply_chain': 'In today\'s dynamic market, we offer flexible delivery solutions that adapt to changing customer demands and production schedules. Our efficient transport models optimize costs while maintaining high service quality for both city and intercity operations.',
    'transport.packing_moving.description': 'We offer specialized packing and moving services for both household and corporate clients, with customized solutions to meet your specific requirements. Our efficient process makes complex relocations simple and hassle-free.',
    'transport.packing_moving.customer_service': 'Our commitment to exceptional customer service sets us apart, ensuring each client receives personalized attention and a seamless moving experience.',

    // Management agreement page
    'mgmtagree.title': 'Management Agreement',
    'mgmtagree.subtitle': 'Professional hotel management services for property owners',
    'mgmtagree.services.title': 'Hotel Management Services',
    'mgmtagree.services.subtitle': 'Comprehensive management solutions for hotel property owners',
    'mgmtagree.description_1': 'Our management agreements provide total management services to third-party hotel proprietors. We charge a percentage of total hotel revenue and other management fees depending on the performance as a percentage from the profit of the hotel unit operations.',
    'mgmtagree.description_2': 'We also charge Sales & Marketing fees based on total number of rooms sold, ensuring our interests are aligned with the success of your property.',
    'mgmtagree.description_3': 'We generally sign agreements for 5-10 years or longer, but it all depends on the place and type of clientele/property.',
    'mgmtagree.features.total_services': 'Total Management Services',
    'mgmtagree.features.total_services_desc': 'Complete management services for third-party hotel proprietors',
    'mgmtagree.features.performance_fees': 'Performance-Based Fees',
    'mgmtagree.features.performance_fees_desc': 'Fees based on percentage of total hotel revenue and profit performance',
    'mgmtagree.features.long_term': 'Long-Term Agreements',
    'mgmtagree.features.long_term_desc': 'Flexible contract terms from 5-10 years or longer based on property needs',
    'mgmtagree.features.sales_marketing': 'Sales & Marketing',
    'mgmtagree.features.sales_marketing_desc': 'Additional fees based on total number of rooms sold and marketing performance',
    'mgmtagree.fee_structure.title': 'Fee Structure',
    'mgmtagree.fee_structure.management_fee': 'Management Fee',
    'mgmtagree.fee_structure.management_fee_desc': 'Percentage of total hotel revenue',
    'mgmtagree.fee_structure.performance_fee': 'Performance Fee',
    'mgmtagree.fee_structure.performance_fee_desc': 'Percentage from hotel profit',
    'mgmtagree.fee_structure.marketing_fee': 'Marketing Fee',
    'mgmtagree.fee_structure.marketing_fee_desc': 'Based on rooms sold',
    
    // Franchise page
    'franchise.title': 'Franchise Agreements',
    'franchise.subtitle': 'International brand franchise opportunities and support',
    'franchise.services.title': 'Franchise Services',
    'franchise.services.subtitle': 'Connecting hotel owners with international brand opportunities',
    'franchise.description_1': 'In our franchise agreements, we evaluate a third-party operator who has prior experience in running a property or the property owner to run the property with qualified staff. Accordingly, under such agreements, we neither own, lease or manage the hotel.',
    'franchise.description_2': 'We derive revenue from a brand royalty or licensing fee which, under most of our franchise agreements, is based on a percentage of total room revenue generated by a hotel. In addition, we collect marketing fees based on total room revenue and reservation fees based on the number of reservations made.',
    'franchise.description_3': 'We can assist third party owners of the hotel to get the brand franchise from international brands who are the brand owners of Holiday Inn, Ramada, Park Inn, Accor etc.',
    'franchise.features.brand_assistance': 'Brand Assistance',
    'franchise.features.brand_assistance_desc': 'Help third-party owners get international brand franchises',
    'franchise.features.qualified_staff': 'Qualified Staff',
    'franchise.features.qualified_staff_desc': 'Evaluate operators with prior experience and qualified staff',
    'franchise.features.marketing_support': 'Marketing Support',
    'franchise.features.marketing_support_desc': 'Access to reservations system and marketing know-how',
    'franchise.features.brand_standards': 'Brand Standards',
    'franchise.features.brand_standards_desc': 'Maintaining specified brand standards and image',
    'franchise.partner_brands.title': 'Partner Brands',
    'franchise.brand_standards.title': 'Brand Standards',
    'franchise.brand_standards.description': 'To maintain our brand image and value, franchisees are obligated to meet specified brand standards. A franchisee also has access to our reservations system and is provided with marketing support and other know-how for operating the hotel.',
    'franchise.contract.title': 'Contract Duration',
    'franchise.contract.description': 'The duration of our franchise agreements are between 5 to 10 years, providing stability and long-term partnership opportunities for property owners.',

    // Clients page
    'clients.title': 'Our Clients',
    'clients.subtitle': 'Trusted by leading companies in the oil and gas industry',
    'clients.description_1': "We are proud to serve some of the world's most respected companies in the energy sector, providing them with reliable and professional services across Kazakhstan. Our extensive client portfolio demonstrates our commitment to excellence and our ability to meet the demanding requirements of international corporations.",
    'clients.description_2': "From major oil companies to engineering contractors, our diverse client base spans across all segments of the energy industry, reflecting our versatile service offerings and proven track record of successful project delivery.",
    'clients.partners.title': 'Our Valued Partners',
    'clients.partnership.title': 'Building Lasting Partnerships',
    'clients.partnership.description': 'For over two decades, we have maintained strong relationships with our clients by consistently delivering exceptional service quality. Our commitment to excellence has made us the preferred partner for major international companies operating in Kazakhstan\'s energy sector.',
    'clients.stats.clients': 'Major Clients',
    'clients.stats.years': 'Years of Partnership',
    'clients.stats.satisfaction': 'Client Satisfaction Focus',
 
    //Contacts page
    'contacts.hero.title': 'Contact Us',
    'contacts.hero.description': 'Get in touch with our team to discuss your business needs and discover how we can help',
    'contacts.form.title': 'Send us a Message',
    'contacts.form.name_label': 'Full Name',
    'contacts.form.name_placeholder': 'Enter your full name',
    'contacts.form.email_label': 'Email Address',
    'contacts.form.email_placeholder': 'Enter your email address',
    'contacts.form.subject_label': 'Subject',
    'contacts.form.subject_placeholder': 'Enter message subject',
    'contacts.form.message_label': 'Message',
    'contacts.form.message_placeholder': 'Enter your message',
    'contacts.form.robot_label': 'I am not a robot',
    'contacts.form.robot_error': 'Please verify that you are not a robot',
    'contacts.form.success_message': 'Message sent successfully! We will get back to you soon.',
    'contacts.form.submit_button': 'Send Message',
    'contacts.info.title': 'Get in Touch',
    'contacts.info.main_office': 'Main Office',
    'contacts.info.address_label': 'Address',
    'contacts.info.phone_label': 'Phone',
    'contacts.info.email_label': 'Email',
    'contacts.info.tel_fax': 'Tel/Fax',
    'contacts.info.mobile': 'Mob',
    'contacts.info.skype': 'Skype',
    'contacts.info.email': 'Email',
    'contacts.departments.title': 'Department Contacts',
    // Department contact information
    'contacts.departments.head_office.name': 'Ritm Oil LLP',
    'contacts.departments.head_office.position': 'Head Office',
    'contacts.departments.head_office.department': 'Administration',
    'contacts.departments.head_office.address': '1a, Druzhba Street, 060007 Atyrau, Republic of Kazakhstan',

    'contacts.departments.hotel.name': 'Hotel & Camp',
    'contacts.departments.hotel.position': 'Hotel Tengri',
    'contacts.departments.hotel.department': 'Hotel & Camp',
    'contacts.departments.hotel.address': '23, Abai Street, 060007 Atyrau, Republic of Kazakhstan',

    'contacts.departments.franchise.name': 'Franchise and Management',
    'contacts.departments.franchise.position': 'Franchise and Management',
    'contacts.departments.franchise.department': 'Franchise and Management',
    'contacts.departments.franchise.address': '1a, Druzhba Street, 060007 Atyrau, Republic of Kazakhstan',

    'contacts.departments.vacancy.name': 'Vacancy',
    'contacts.departments.vacancy.position': 'HR Department',
    'contacts.departments.vacancy.department': 'Vacancy',
    'contacts.departments.vacancy.address': '1a, Druzhba Street, 060007 Atyrau, Republic of Kazakhstan',
  },
  ru: {
    // Meta
    'meta.title': 'ТОО «Ритм Ойл» — Услуги для нефтяной промышленности в Казахстане',
    'meta.description': 'Ведущий поставщик гостиничного бизнеса, кейтеринга, транспорта и логистики для нефтегазовой отрасли Казахстана',

    // Common
    'common.learn_more': 'Узнать больше',
    'common.contact_us': 'Связаться с нами',

    // Hero
    'hero.title': 'Добро пожаловать в Ritm Oil LLP',
    'hero.subtitle': 'Ведущий поставщик комплексных услуг для нефтяной отрасли Казахстана',
    'home.hero.description': 'С 2004 года предоставляем комплексные услуги в области логистики, кейтеринга и размещения для нефтегазовой отрасли Казахстана.',

    // Home page
    'home.about.title': 'О компании Ritm Oil LLP',
    'home.about.description_1': 'ТОО "Ritm Oil" начало свою деятельность в 2001 году в сфере торговли нефтью и предоставления логистических услуг подрядчикам KPO b.v. в городе Аксай, Западно-Казахстанская область. Мы выполняли техническое обслуживание объектов KPO b.v., включая демонтаж и утилизацию некоторых видов временных зданий и сооружений.',
    'home.about.description_2': 'В настоящее время компания специализируется на управлении объектами для NCOC, гостиничных услугах, кейтеринге, транспортных услугах и переработке отходов для компаний нефтегазового сектора Республики Казахстан.',
    'home.about.description_3': 'Компания располагает гостиницей, вахтовыми поселками и офисами в городах Атырау и Алматы. Главный актив компании — это команда из 300 сотрудников. Ключевые сотрудники управления работают в Ritm Oil более 15 лет.',
    'home.about.quote': '"Гостеприимство — наш подход"',
    'home.services.title': 'Наши услуги',
    'home.services.subtitle': 'Комплексные решения для нефтегазовой отрасли',
    'home.services.hotel.title': 'Гостиничный бизнес',
    'home.services.hotel.description': 'Профессиональное управление гостиницами и размещением',
    'home.services.catering.title': 'Кейтеринг',
    'home.services.catering.description': 'Качественное питание и управление вахтовыми поселками',
    'home.services.transport.title': 'Транспорт и логистика',
    'home.services.transport.description': 'Надежные транспортные и логистические услуги',
    'home.services.management.title': 'Управленческие услуги',
    'home.services.management.description': 'Профессиональное управление и консалтинг',
    'home.services.franchise.title': 'Франшизные услуги',
    'home.services.franchise.description': 'Поддержка и сопровождение бренда и франшизы',
    'home.cta.title': 'Готовы к сотрудничеству?',
    'home.cta.subtitle': 'Свяжитесь с нами, чтобы обсудить ваши бизнес-потребности',
    'home.cta.button': 'Связаться с нами',

    // Header
    'header.main': 'Главная',
    'header.about.title': 'О компании',
    'header.about.mission': 'Миссия и цели',
    'header.about.history': 'История компании',
    'header.about.management': 'Руководство',
    'header.about.assets': 'Нематериальные активы',
    'header.services.title': 'Услуги',
    'header.services.hotel': 'Гостиничный бизнес',
    'header.services.catering': 'Кейтеринг и управление поселками',
    'header.services.transport': 'Транспорт и логистика',
    'header.services.management': 'Управляющий договор',
    'header.services.franchise': 'Франчайзинговый договор',
    'header.clients': 'Клиенты',
    'header.contacts': 'Контакты',
    'img.logo' : '/src/img/logo_ritmoil_rus.png',

    // Footer
    'footer.description': 'Ведущий поставщик комплексных услуг в нефтяной отрасли: гостиничный бизнес, кейтеринг, транспортная логистика и управленческие решения.',
    'footer.contact.title': 'Контактная информация',
    'footer.contact.main_office': 'Главный офис',
    'footer.contact.general_inquiries': 'Общие вопросы',
    'footer.contact.location': 'ул. Дружбы, 1А, г. Атырау, Казахстан',
    'footer.contact.head_office': 'Штаб-квартира',
    'footer.quick_links': 'Быстрые ссылки',
    'footer.links.mission': 'Миссия',
    'footer.links.hotel': 'Гостиничный бизнес',
    'footer.links.history': 'История',
    'footer.links.catering': 'Кейтеринг',
    'footer.links.management': 'Управление',
    'footer.links.transport': 'Транспорт',
    'footer.links.clients': 'Клиенты',
    'footer.links.contacts': 'Контакты',
    'footer.copyright': '© 2025 ТОО "Ritm Oil". Все права защищены.',

    // Mission page
    "mission.title": "Миссия и Цели",
    "mission.subtitle": "Наша приверженность к совершенству в обслуживании нефтегазовой отрасли",
    "mission.our_mission": "Наша миссия : ",
    "mission.our_purposes": "Наши цели : ",
    "mission.statement": "Предоставлять лучшие услуги нашим клиентам на основе международных бизнес-стандартов",
    "mission.client_excellence": "Клиентоориентированность",
    "mission.client_excellence_desc": "Превосходить ожидания клиентов, предоставляя услуги высокого качества.",
    "mission.employee_development": "Развитие сотрудников",
    "mission.employee_development_desc": "Стать привлекательной компанией для развития сотрудников.",
    "mission.social_responsibility": "Социальная ответственность",
    "mission.social_responsibility_desc": "Быть социально ответственной компанией.",
    "mission.business_growth": "Рост бизнеса",
    "mission.business_growth_desc": "Увеличивать капитализацию бизнеса и прибыль учредителей.",
    "mission.iso.title": "Международные стандарты",
    "mission.iso.description": "Управление Ritm Oil LLP соответствует международному стандарту ISO 22000:2005, что подтверждается сертификатом № TFSMS/16/XX/AN от 18.04.2016, выданным итальянской аудиторской компанией \"Rina Service SPA\".",
    "mission.motto": "В одном ритме к общему успеху!",

    // History page
    "history.title": "История компании",
    "history.subtitle": "Более двух десятилетий превосходства в сфере нефтегазовых услуг",
    "history.journey.title": "Наш путь",
    "history.journey.description": "Компания Ritm Oil LLP предоставляет услуги по размещению, питанию и техническому обслуживанию компаний нефтегазового сектора Республики Казахстан более 20 лет. В начале деятельности Ritm Oil осуществляла техническое обслуживание на объектах KPO b.v., включая демонтаж и утилизацию различных типов временных зданий и сооружений.",
    "history.milestones.title": "Ключевые этапы",
    "history.milestones.2001": "Основание компании — начало деятельности в торговле нефтью и логистических услугах для подрядчиков KPO b.v. в городе Аксай",
    "history.milestones.2003": "Строительство и ввод в эксплуатацию отеля Green в городе Атырау",
    "history.milestones.2005": "Приобретение отеля Zhuldyz в городе Аксай, Западно-Казахстанская область",
    "history.milestones.2006": "Строительство отеля Tengri в городе Атырау",
    "history.milestones.2007": "Ввод в эксплуатацию отеля Tengri для корпорации Tsesna в городе Астана под собственной торговой маркой",
    "history.milestones.2009": "Строительство вахтового лагеря Ritm для персонала подрядчиков Agip KCO",
    "history.milestones.2013": "Выигрыш тендера на услуги кейтеринга и технического обслуживания учебного центра Agip KCO",
    "history.milestones.2015": "Строительство и ввод в эксплуатацию отеля Ramada в городе Алматы по франшизе американской гостиничной сети \"Wyndham Worldwide\"",
    "history.milestones.2016": "Начало предоставления услуг управления объектами и кейтеринга для NCOC NV",
    "history.today.title": "Сегодня",
    "history.today.properties.title": "Множество объектов",
    "history.today.properties.description": "Отели, лагеря и офисы по всему Казахстану",
    "history.today.locations.title": "Стратегические локации",
    "history.today.locations.description": "Операции в Атырау, Алматы и Аксае",
    "history.today.experience.title": "Более 20 лет",
    "history.today.experience.description": "Опыт и непрерывный рост",

    // Management page
    "management.title": "Руководство",
    "management.subtitle": "Профессиональное руководство, обеспечивающее наш успех",
    "management.philosophy.title": "Наша философия лидерства",
    "management.philosophy.description1": "Как быстро развивающаяся компания, мы всегда считали важным строить наши дальнейшие шаги на прочной основе. Мы верим, что бизнес ценен, когда его инфраструктура сильна. Мы посвятили команду, обладающую знаниями и креативностью, для распознавания ежедневных потребностей рынков и поддержки наших операций с целью быть актуальными и инновационными.",
    "management.philosophy.description2": "Наши успехи являются результатом преданных усилий профессиональной команды под руководством следующих опытных специалистов:",
    "management.team.chairman.name": "Татиев Мурат Петрович",
    "management.team.chairman.position": "Председатель Совета директоров",
    "management.team.chairman.description": "Г-н Татиев М. имеет два высших образования, включая экономику по специальности \"Финансы и кредит\", и 30 лет опыта на руководящих административных должностях. С момента основания компании он отвечает за стратегическое планирование, организацию и управление персоналом.",
    "management.team.general_director.name": "Саха Субхасис",
    "management.team.general_director.position": "Генеральный директор",
    "management.team.general_director.description": "Опыт г-на Саха в индустрии гостеприимства охватывает 25 лет в различных регионах Индии и Казахстана. В 2002 году, на раннем этапе основания Ritmoil LLP, г-н Саха присоединился к компании в качестве генерального менеджера, контролируя операции всех объектов и играя ключевую роль в расширении и развитии будущих отелей. В 2010 году он стал генеральным директором и соучредителем \"Ritmoil LLP\". Г-н Саха получил высшее образование в области гостиничного менеджмента в одном из самых престижных институтов Индии — IHM, Бангалор.",
    "management.team.operations_manager.name": "Рой Басаб",
    "management.team.operations_manager.position": "Генеральный менеджер по операциям и маркетингу",
    "management.team.operations_manager.description": "Г-н Рой, PhD, окончил магистратуру Азербайджанского института. Он имеет большой опыт работы в странах СНГ в области маркетинга и работал в различных регионах СНГ. Он работает в Ritm Oil LLP с 2010 года и был непосредственно вовлечен в развитие компании на различных уровнях через сотрудничество с крупными нефтяными компаниями и международно признанными строительными фирмами.",
    "management.team.hr_director.name": "Елизарова Ольга Владимировна",
    "management.team.hr_director.position": "Директор по персоналу",
    "management.team.hr_director.description": "Г-жа Елизарова О., имея академическое образование в области экономики и права, работает в «RitmOil» с основания компании в должности директора по персоналу. Она отвечает за организацию работы с персоналом и административные задачи.",
    "management.team.finance_director.name": "Габдуллин Нурлан Имангазиевич",
    "management.team.finance_director.position": "Финансовый директор",
    "management.team.finance_director.description": "Г-н Габдуллин Н. отвечает за управление финансами группы Ritm, слияния и поглощения, закупки и юридические функции. Имея более 14 лет опыта в группе Ritm на различных финансовых должностях, он приносит уникальное понимание финансовой ответственности в Ritmoil. Также отвечает за все переговоры с банками и государственным финансовым институтом \"ДАМУ\". Г-н Габдуллин Н. имеет докторскую степень в экономике.",
    "management.team.chief_accountant.name": "Калимукашева Тамара Ермековна",
    "management.team.chief_accountant.position": "Главный бухгалтер",
    "management.team.chief_accountant.description": "Г-жа Калимукашева Т.Е. работает главным бухгалтером с 2003 года. Под ее руководством в компании внедрены автоматизированные бухгалтерские и налоговые учеты на базе платформы 1С. Создание эффективной учетной политики позволило успешно вести финансовую деятельность ассоциации.",
    "management.certifications.title": "Международные стандарты",
    "management.certifications.description": "Управление компанией Ritm Oil соответствует международным стандартам, что подтверждено сертификатами:",
    
    // Assets page
    'assets.title': 'Нематериальные активы',
    'assets.subtitle': 'Наши ценные лицензии, сертификаты и надежные партнерства',
    'assets.licenses.title': 'Лицензии и разрешения',
    'assets.licenses.description': 'Вместе с основными средствами "Ritm Oil" обладает всеми необходимыми лицензиями для ведения гостиничного бизнеса, квотами и разрешениями на работу для экспатов, зарегистрированным в Торгово-промышленной палате (ТПП) сертификатом регистрации товарного знака "Tengri".',
    'assets.licenses.business.title': 'Лицензии на гостиничный бизнес',
    'assets.licenses.business.description': 'Все необходимые разрешения для работы гостиницы',
    'assets.licenses.trademark.title': 'Регистрация товарных знаков',
    'assets.licenses.trademark.description': 'Товарный знак "Tengri"',
    'assets.insurance.title': 'Страховое покрытие',
    'assets.insurance.description': 'Все наши объекты недвижимости застрахованы в "Евразия Страхование", лидере страхового рынка Казахстана.',
    'assets.clients.title': 'Стабильное клиентское портфолио',
    'assets.clients.description': 'Одним из самых важных нематериальных активов является наличие стабильной и постоянно растущей клиентской базы, включая крупнейшие мировые компании:',
    'assets.clients.list': 'NCOC, Parker Drilling, Saipem, Ersai, Sicim S.p.A., Wagenborg, FMC, Petroleum Facilities Е&C Limited, Weatherford, Baker Hughes, Bolashak Atyrau, Fircroft Engineering, Bonatti, Kaz Story Service, PSN KazStroy, Punj Lloyd, KCA-Deutag, Worley Parsons, Corporation JGС-Marubeni, ССС, Ligabue Central Asia, Bateman, Kentech',
    'assets.clients.footer': 'и многие другие.',
    'assets.financial.title': 'Финансовое доверие',
    'assets.financial.description': 'Мы гордимся заслуженным доверием инвесторов и банков, которые финансировали все наши проекты и поддерживали наше динамичное развитие.',

    // Hotel page
    'hotel.title': 'Гостиничный бизнес',
    'hotel.subtitle': 'Премиальные услуги проживания в самом сердце Атырау',
    'hotel.tengri.title': 'Гостиница Tengri',
    'hotel.tengri.location': 'Расположена в центре Атырау',
    'hotel.tengri.description_1': 'Гостиница находится в центре Атырау. В ней 60 номеров, из которых 15 — апартаменты с мини-кухней, 45 — стандартные номера. Каждый номер оснащён телекоммуникационными и интернет-соединениями, кондиционером и многоязычной спутниковой телевизионной системой.',
    'hotel.tengri.description_2': 'Наши гости особенно ценят ресторан под руководством шеф-поваров из Италии и Индии. Бар в гостинице позволяет клиентам отдыхать с коллегами и друзьями или проводить деловые встречи. В лаундж-баре установлена широкоформатная проекционная система, где гости могут смотреть различные спортивные события.',
    'hotel.tengri.description_3': 'Дополнительной привлекательностью бара является живая музыка по средам и субботам, организованная одной из самых известных музыкальных групп города Атырау.',
    'hotel.amenities.rooms': '60 номеров',
    'hotel.amenities.rooms_desc': '15 апартаментов с мини-кухней, 45 стандартных номеров',
    'hotel.amenities.connectivity': 'Современная связь',
    'hotel.amenities.connectivity_desc': 'Телекоммуникации и интернет в каждом номере',
    'hotel.amenities.cuisine': 'Итальянская и индийская кухня',
    'hotel.amenities.cuisine_desc': 'Ресторан под руководством шеф-поваров из Италии и Индии',
    'hotel.amenities.entertainment': 'Живые развлечения',
    'hotel.amenities.entertainment_desc': 'Живая музыка по средам и субботам',
    'hotel.booking.title': 'Забронируйте проживание',
    'hotel.booking.description': 'Ощутите комфорт и гостеприимство в гостинице Tengri',
    'hotel.booking.button': 'Забронировать сейчас',

    // Catering page
    'catering.title': 'Кейтеринг и управление лагерем',
    'catering.subtitle': 'Комплексные услуги питания и решения по управлению лагерем',
    'catering.services.title': 'Наши услуги кейтеринга',
    'catering.services.subtitle': 'Предоставление исключительных услуг питания и управления лагерями по всему Казахстану',
    'catering.description_1': 'Помимо управления "Ritm Camp" и "Punj Lloyd", мы оказывали полный комплекс услуг по управлению лагерем, включая кейтеринг, техническое обслуживание и уборку для "Consolidate Contractors Company" (CCC) на 1800 человек в день до 2011 года.',
    'catering.description_2': 'Высокий стандарт обслуживания питания помог нам выиграть тендер в 2013 году от Agip KCO на предоставление кейтеринга и клининговых услуг в "Учебном центре Agip" в Атырау.',
    'catering.description_3': 'Мы организуем и предоставляем выездные услуги кейтеринга на любых специальных мероприятиях клиентов.',
    'catering.services.camp_management': 'Управление лагерем',
    'catering.services.camp_management_desc': 'Полный комплекс услуг по управлению лагерем, включая кейтеринг, техническое обслуживание и уборку',
    'catering.services.high_capacity': 'Большая пропускная способность',
    'catering.services.high_capacity_desc': 'Обслуживание до 1800 человек в день в различных локациях',
    'catering.services.quality_food': 'Качественное питание',
    'catering.services.quality_food_desc': 'Высокий стандарт питания, позволивший выиграть крупные тендеры',
    'catering.services.event_catering': 'Кейтеринг на мероприятия',
    'catering.services.event_catering_desc': 'Организация и предоставление выездных кейтеринговых услуг на специальных мероприятиях',
    'catering.achievements.title': 'Ключевые достижения',
    'catering.achievements.people_served': 'Обслужено людей в день',
    'catering.achievements.agip_tender': 'Выигран тендер Agip KCO',
    'catering.achievements.years_experience': 'Лет опыта',

    // transport page
    'transport.title': 'Транспорт и логистика',
    'transport.subtitle': 'Комплексные логистические решения для нефтегазовой отрасли',
    'transport.services.title': 'Транспортные и логистические услуги',
    'transport.services.subtitle': 'Современные логистические решения, разработанные для требовательного рынка',
    'transport.full_range': 'Полный спектр логистики',
    'transport.full_range_desc': 'Полный комплекс логистических услуг по управлению грузопотоками и цепочками поставок',
    'transport.just_in_time': 'Доставка точно в срок',
    'transport.just_in_time_desc': 'Эффективное планирование доставки в соответствии с потребностями потребителей и производственными графиками',
    'transport.packing_moving': 'Упаковка и переезд',
    'transport.packing_moving_desc': 'Профессиональные услуги по упаковке и перевозке бытовых и корпоративных грузов',
    'transport.city_transport': 'Городской и междугородний транспорт',
    'transport.city_transport_desc': 'Надежные транспортные услуги в пределах города и между регионами',
    'transport.main_content.overview': 'ТОО "Ritm Oil" предоставляет комплексные логистические услуги по управлению грузопотоками и операциями цепочки поставок, специализируясь на нефтегазовой отрасли.',
    'transport.main_content.supply_chain': 'В условиях динамичного рынка мы предлагаем гибкие решения по доставке, адаптирующиеся к изменяющимся требованиям клиентов и производственным графикам. Наши эффективные модели транспорта оптимизируют расходы при сохранении высокого качества обслуживания как в городе, так и междугородних перевозках.',
    'transport.packing_moving.description': 'Мы предлагаем специализированные услуги по упаковке и переезду как для частных, так и корпоративных клиентов с индивидуальным подходом к вашим требованиям. Наш эффективный процесс делает сложные переезды простыми и удобными.',
    'transport.packing_moving.customer_service': 'Наше стремление к исключительному сервису выделяет нас, гарантируя каждому клиенту персональное внимание и беспроблемный опыт переезда.',

    // Management agreement page
    'mgmtagree.title': 'Договор управления',
    'mgmtagree.subtitle': 'Профессиональные услуги по управлению отелями для собственников недвижимости',
    'mgmtagree.services.title': 'Услуги по управлению отелями',
    'mgmtagree.services.subtitle': 'Комплексные решения по управлению для собственников гостиничной недвижимости',
    'mgmtagree.description_1': 'Наши договоры управления предусматривают полное управление гостиницами третьих лиц. Мы взимаем процент от общего дохода отеля и другие управленческие сборы, которые зависят от показателей деятельности и прибыли от операций гостиничного подразделения.',
    'mgmtagree.description_2': 'Также мы взимаем оплату за продажи и маркетинг, основанную на общем количестве проданных номеров, что обеспечивает совпадение наших интересов с успехом вашей недвижимости.',
    'mgmtagree.description_3': 'Обычно мы заключаем договоры на срок от 5 до 10 лет и более, однако сроки зависят от места расположения и типа клиентуры/недвижимости.',
    'mgmtagree.features.total_services': 'Полный комплекс управления',
    'mgmtagree.features.total_services_desc': 'Полное управление гостиницами третьих лиц',
    'mgmtagree.features.performance_fees': 'Оплата по результатам',
    'mgmtagree.features.performance_fees_desc': 'Сборы в зависимости от процента общего дохода и прибыли отеля',
    'mgmtagree.features.long_term': 'Долгосрочные соглашения',
    'mgmtagree.features.long_term_desc': 'Гибкие условия контракта от 5 до 10 лет и более, в зависимости от потребностей недвижимости',
    'mgmtagree.features.sales_marketing': 'Продажи и маркетинг',
    'mgmtagree.features.sales_marketing_desc': 'Дополнительные сборы на основе количества проданных номеров и маркетинговой деятельности',
    'mgmtagree.fee_structure.title': 'Структура оплаты',
    'mgmtagree.fee_structure.management_fee': 'Управленческий сбор',
    'mgmtagree.fee_structure.management_fee_desc': 'Процент от общего дохода отеля',
    'mgmtagree.fee_structure.performance_fee': 'Сбор за результативность',
    'mgmtagree.fee_structure.performance_fee_desc': 'Процент от прибыли отеля',
    'mgmtagree.fee_structure.marketing_fee': 'Маркетинговый сбор',
    'mgmtagree.fee_structure.marketing_fee_desc': 'На основе проданных номеров',

    // Franchise page
    'franchise.title': 'Франчайзинговые соглашения',
    'franchise.subtitle': 'Возможности и поддержка международных брендов франшизы',
    'franchise.services.title': 'Франчайзинговые услуги',
    'franchise.services.subtitle': 'Связываем владельцев отелей с международными брендами',
    'franchise.description_1': 'В наших франчайзинговых соглашениях мы оцениваем стороннего оператора с опытом управления объектами или владельца недвижимости, который управляет им с квалифицированным персоналом. В соответствии с такими соглашениями мы не являемся владельцами, арендодателями или управляющими отелем.',
    'franchise.description_2': 'Наш доход формируется за счёт роялти или лицензионных сборов, которые в большинстве наших договоров основаны на проценте от общего дохода от номеров. Дополнительно мы взимаем маркетинговые сборы на основе дохода от номеров и сборы за бронирование по количеству бронирований.',
    'franchise.description_3': 'Мы помогаем владельцам отелей получить франшизы международных брендов, таких как Holiday Inn, Ramada, Park Inn, Accor и других.',
    'franchise.features.brand_assistance': 'Поддержка бренда',
    'franchise.features.brand_assistance_desc': 'Помощь владельцам в получении международных франшиз',
    'franchise.features.qualified_staff': 'Квалифицированный персонал',
    'franchise.features.qualified_staff_desc': 'Оценка операторов с опытом и квалифицированным персоналом',
    'franchise.features.marketing_support': 'Маркетинговая поддержка',
    'franchise.features.marketing_support_desc': 'Доступ к системе бронирования и маркетинговым знаниям',
    'franchise.features.brand_standards': 'Стандарты бренда',
    'franchise.features.brand_standards_desc': 'Соблюдение установленных стандартов и имиджа бренда',
    'franchise.partner_brands.title': 'Партнёрские бренды',
    'franchise.brand_standards.title': 'Стандарты бренда',
    'franchise.brand_standards.description': 'Для поддержания имиджа и ценности бренда франчайзи обязаны соблюдать определённые стандарты бренда. Франчайзи также получает доступ к системе бронирования и маркетинговую поддержку и другие знания для управления отелем.',
    'franchise.contract.title': 'Срок действия договора',
    'franchise.contract.description': 'Срок наших франчайзинговых соглашений составляет от 5 до 10 лет, обеспечивая стабильность и долгосрочное партнёрство для владельцев недвижимости.',

    // Clients page
    'clients.title': 'Наши клиенты',
    'clients.subtitle': 'Доверие ведущих компаний нефтегазовой отрасли',
    'clients.description_1': "Мы гордимся тем, что обслуживаем одни из самых уважаемых компаний в энергетическом секторе, предоставляя им надежные и профессиональные услуги по всему Казахстану. Наш широкий портфель клиентов подтверждает нашу приверженность качеству и способность соответствовать высоким требованиям международных корпораций.",
    'clients.description_2': "От крупных нефтяных компаний до инженерных подрядчиков — наша разнообразная клиентская база охватывает все сегменты энергетической отрасли, отражая наш универсальный спектр услуг и подтвержденный опыт успешной реализации проектов.",
    'clients.partners.title': 'Наши ценные партнеры',
    'clients.partnership.title': 'Строим прочные партнерские отношения',
    'clients.partnership.description': 'На протяжении более двух десятилетий мы поддерживаем крепкие отношения с нашими клиентами, постоянно обеспечивая исключительное качество обслуживания. Наша приверженность совершенству сделала нас предпочтительным партнером для крупных международных компаний, работающих в энергетическом секторе Казахстана.',
    'clients.stats.clients': 'Крупные клиенты',
    'clients.stats.years': 'Лет партнерства',
    'clients.stats.satisfaction': 'Ориентация на удовлетворенность клиентов',

    //Contacts page
    'contacts.hero.title': 'Свяжитесь с нами',
    'contacts.hero.description': 'Свяжитесь с нашей командой, чтобы обсудить ваши бизнес-потребности и узнать, как мы можем помочь',
    'contacts.form.title': 'Отправить сообщение',
    'contacts.form.name_label': 'Полное имя',
    'contacts.form.name_placeholder': 'Введите ваше полное имя',
    'contacts.form.email_label': 'Адрес электронной почты',
    'contacts.form.email_placeholder': 'Введите ваш email',
    'contacts.form.subject_label': 'Тема',
    'contacts.form.subject_placeholder': 'Введите тему сообщения',
    'contacts.form.message_label': 'Сообщение',
    'contacts.form.message_placeholder': 'Введите ваше сообщение',
    'contacts.form.robot_label': 'Я не робот',
    'contacts.form.robot_error': 'Пожалуйста, подтвердите, что вы не робот',
    'contacts.form.success_message': 'Сообщение успешно отправлено! Мы свяжемся с вами в ближайшее время.',
    'contacts.form.submit_button': 'Отправить сообщение',
    'contacts.info.title': 'Связаться с нами',
    'contacts.info.main_office': 'Головной офис',
    'contacts.info.address_label': 'Адрес',
    'contacts.info.phone_label': 'Телефон',
    'contacts.info.email_label': 'Электронная почта',
    'contacts.info.tel_fax': 'Тел/Факс',
    'contacts.info.mobile': 'Моб.',
    'contacts.info.skype': 'Skype',
    'contacts.info.email': 'Email',
    'contacts.departments.title': 'Контакты отделов',
    // Department contact information
    'contacts.departments.head_office.name': 'ТОО Ritm Oil',
    'contacts.departments.head_office.position': 'Головной офис',
    'contacts.departments.head_office.department': 'Администрация',
    'contacts.departments.head_office.address': 'ул. Дружба, 1а, 060007 Атырау, Республика Казахстан',

    'contacts.departments.hotel.name': 'Отель и лагерь',
    'contacts.departments.hotel.position': 'Отель Тенгри',
    'contacts.departments.hotel.department': 'Отель и лагерь',
    'contacts.departments.hotel.address': 'ул. Абая, 23, 060007 Атырау, Республика Казахстан',

    'contacts.departments.franchise.name': 'Франчайзинг и управление',
    'contacts.departments.franchise.position': 'Франчайзинг и управление',
    'contacts.departments.franchise.department': 'Франчайзинг и управление',
    'contacts.departments.franchise.address': 'ул. Дружба, 1а, 060007 Атырау, Республика Казахстан',

    'contacts.departments.vacancy.name': 'Вакансии',
    'contacts.departments.vacancy.position': 'Отдел кадров',
    'contacts.departments.vacancy.department': 'Вакансии',
    'contacts.departments.vacancy.address': 'ул. Дружба, 1а, 060007 Атырау, Республика Казахстан',

  },
  kz: {
    //Meta
    'meta.title': 'Ritm Oil ЖШС – Мұнай-газ саласындағы қызметтер, Қазақстан',
    'meta.description': 'Қазақстандағы мұнай-газ өнеркәсібіне арналған қонақ үй, тамақтандыру және логистика қызметтерінің жетекші жеткізушісі',

    // Common
    'common.learn_more': 'Толығырақ',
    'common.contact_us': 'Байланысу',

    // Hero
    'hero.title': 'Ritm Oil LLP компаниясына қош келдіңіз',
    'hero.subtitle': 'Қазақстандағы мұнай өнеркәсібіне арналған кешенді қызметтердің жетекші жеткізушісі',
    'home.hero.description': '2004 жылдан бері Қазақстандағы мұнай-газ саласына логистика, тамақтандыру және орналастыру бойынша кешенді қызметтер ұсынып келеміз.',

    // Home page
    'home.about.title': 'Ritm Oil LLP туралы',
    'home.about.description_1': '"Ritm Oil" ЖШС өз қызметін 2001 жылы бастады. Ол кезде компания мұнай саудасы және БҚО, Аксай қаласындағы KPO b.v. мердігерлеріне логистикалық қызметтер көрсетті. Сондай-ақ, KPO b.v. нысандарында техникалық қызмет көрсетіп, кейбір уақытша ғимараттар мен құрылыстарды бөлшектеу және жою жұмыстарын атқарды.',
    'home.about.description_2': 'Қазіргі уақытта компания NCOC нысандарын басқаруға, қонақ үй қызметіне, тамақтандыруға, көлік қызметтеріне және мұнай-газ саласында жұмыс істейтін компанияларға арналған қалдықтарды қайта өңдеуге бағытталған.',
    'home.about.description_3': 'Компанияның Атырау және Алматы қалаларында қонақ үйі, вахталық кенттері және кеңселері бар. Ritm Oil компаниясының негізгі капиталы – 300 адамнан тұратын ұжым. Басқарушы құрамының негізгі қызметкерлері компанияда 15 жылдан астам жұмыс істеп келеді.',
    'home.about.quote': '"Қонақжайлылық — біздің көзқарасымыз"',
    'home.services.title': 'Біздің қызметтер',
    'home.services.subtitle': 'Мұнай-газ саласына арналған кешенді шешімдер',
    'home.services.hotel.title': 'Қонақ үй қызметі',
    'home.services.hotel.description': 'Кәсіби қонақ үйді басқару және орналастыру қызметтері',
    'home.services.catering.title': 'Тамақтандыру қызметтері',
    'home.services.catering.description': 'Сапалы тамақтандыру және вахталық кенттерді басқару шешімдері',
    'home.services.transport.title': 'Көлік және логистика',
    'home.services.transport.description': 'Сенімді көлік және логистикалық қызметтер',
    'home.services.management.title': 'Басқару қызметтері',
    'home.services.management.description': 'Кәсіби басқару және консалтинг',
    'home.services.franchise.title': 'Франшиза қызметтері',
    'home.services.franchise.description': 'Брендпен жұмыс істеу және франшизаны қолдау',
    'home.cta.title': 'Бізбен серіктес болғыңыз келе ме?',
    'home.cta.subtitle': 'Бизнес қажеттіліктеріңізді талқылау үшін бізге хабарласыңыз',
    'home.cta.button': 'Хабарласыңыз',

    // Header
    'header.main': 'Басты бет',
    'header.about.title': 'Компания туралы',
    'header.about.mission': 'Миссия және мақсаттар',
    'header.about.history': 'Компания тарихы',
    'header.about.management': 'Басқару',
    'header.about.assets': 'Материалдық емес активтер',
    'header.services.title': 'Қызметтер',
    'header.services.hotel': 'Қонақ үй бизнесі',
    'header.services.catering': 'Тамақтандыру және кенттерді басқару',
    'header.services.transport': 'Көлік және логистика',
    'header.services.management': 'Басқару келісімі',
    'header.services.franchise': 'Франшиза келісімі',
    'header.clients': 'Клиенттер',
    'header.contacts': 'Байланыс',
    'img.logo' : '/src/img/logo_ritmoil_kz.png',

    // Footer
    'footer.description': 'Мұнай өнеркәсібіне арналған кешенді қызметтердің жетекші жеткізушісі: қонақ үй бизнесі, тамақтандыру, көлік логистикасы және басқару шешімдері.',
    'footer.contact.title': 'Байланыс ақпараты',
    'footer.contact.main_office': 'Басты кеңсе',
    'footer.contact.general_inquiries': 'Жалпы сұрақтар',
    'footer.contact.location': 'Атырау қаласы, Достық көшесі, 1А, Қазақстан',
    'footer.contact.head_office': 'Бас кеңсе',
    'footer.quick_links': 'Жылдам сілтемелер',
    'footer.links.mission': 'Миссия',
    'footer.links.hotel': 'Қонақ үй бизнесі',
    'footer.links.history': 'Тарих',
    'footer.links.catering': 'Тамақтандыру',
    'footer.links.management': 'Басқару',
    'footer.links.transport': 'Көлік',
    'footer.links.clients': 'Клиенттер',
    'footer.links.contacts': 'Байланыс',
    'footer.copyright': '© 2025 "Ritm Oil" ЖШС. Барлық құқықтар қорғалған.',

    // Mission page
    'mission.title': 'Миссия мен мақсаттар',
    'mission.subtitle': 'Мұнай-газ саласына сапалы қызмет көрсетуге деген адалдық',
    'mission.our_mission': 'Біздің миссиямыз: ',
    'mission.our_purposes': 'Біздің мақсаттарымыз: ',
    'mission.statement': 'Халықаралық бизнес стандарттарына сәйкес клиенттерімізге ең жақсы қызмет көрсету',
    'mission.client_excellence': 'Клиенттердің қанағаттануы',
    'mission.client_excellence_desc': 'Жоғары сапалы қызмет көрсетумен клиенттердің күткенінен асып түсу',
    'mission.employee_development': 'Қызметкерлердің дамуы',
    'mission.employee_development_desc': 'Қызметкерлерді дамытуға тартымды компания болу',
    'mission.social_responsibility': 'Әлеуметтік жауапкершілік',
    'mission.social_responsibility_desc': 'Әлеуметтік жауапты компания болу',
    'mission.business_growth': 'Бизнестің өсуі',
    'mission.business_growth_desc': 'Бизнестің капитализациясын және құрылтайшылардың пайдасын арттыру',
    'mission.iso.title': 'Халықаралық стандарттар',
    'mission.iso.description': 'Ritm Oil ЖК басқармасы халықаралық ISO 22000:2005 стандартына сәйкес келеді, бұл Италиялық аудиттік компания «Rina Service SPA» берген N TFSMS/16/XX/AN № куәлігімен расталған (18.04.2016 ж.)',
    'mission.motto': 'Жалпы табысқа бір ырғақпен!',

    // History page
    'history.title': 'Компанияның тарихы',
    'history.subtitle': 'Мұнай-газ қызмет көрсету саласындағы 20 жылдан астам үздік тәжірибе',
    'history.journey.title': 'Біздің жолымыз',
    'history.journey.description': 'Ritm Oil ЖК Қазақстан Республикасының мұнай-газ секторында жұмыс істейтін компанияларға тұрғын үй, тамақтану және қызмет көрсету қызметтерін 20 жылдан астам уақыт ұсынады. Бизнесіміздің басында Ritm Oil KPO b.v. учаскелерінде техникалық қызмет көрсету жұмыстарын жүргізген, оның ішінде түрлі уақытша ғимараттарды демонтаждау және жою жұмыстары болды.',
    'history.milestones.title': 'Негізгі кезеңдер',
    'history.milestones.2001': 'Компания құрылды - Aksai қаласында KPO b.v. мердігерлеріне мұнай саудасы мен логистика қызметтерін ұсыну басталды',
    'history.milestones.2003': 'Atyrau қаласында Green қонақүйі салынды және пайдалануға берілді',
    'history.milestones.2005': 'Aksay қаласында, Батыс Қазақстан облысында Жұлдыз қонақүйі сатып алынды',
    'history.milestones.2006': 'Atyrau қаласында Tengri қонақүйі салынды',
    'history.milestones.2007': 'Astana қаласында Tsesna корпорациясы үшін Tengri қонақүйі өз брендімізбен пайдалануға берілді',
    'history.milestones.2009': 'Agip KCO мердігерлерінің қызметкерлеріне арналған Ritm ауысым лагерін салды',
    'history.milestones.2013': 'Agip KCO оқу орталығына тамақтандыру және қызмет көрсету бойынша тендерді жеңіп алды',
    'history.milestones.2015': 'Almaty қаласында «Wyndham Worldwide» американдық қонақүй желісінің франшизасы ретінде Ramada қонақүйі салынды және пайдалануға берілді',
    'history.milestones.2016': 'NCOC NV үшін объектіні басқару және тамақтандыру қызметтерін ұсына бастады',
    'history.today.title': 'Бүгін',
    'history.today.properties.title': 'Көптеген нысандар',
    'history.today.properties.description': 'Қазақстан бойынша қонақүйлер, лагерлер және кеңселер',
    'history.today.locations.title': 'Стратегиялық орналасулар',
    'history.today.locations.description': 'Atyrau, Almaty және Aksai қалаларындағы операциялар',
    'history.today.experience.title': '20+ жыл',
    'history.today.experience.description': 'Тәжірибе мен үздіксіз даму',

    // Management page
    'management.title': 'Басқару',
    'management.subtitle': 'Біздің табысымызға жетекшілік ететін кәсіби көшбасшылық',
    'management.philosophy.title': 'Басқару философиямыз',
    'management.philosophy.description1': 'Жылдам дамып келе жатқан компания ретінде, біз әрдайым әрі қарай қадам басқанда сенімді платформаларға сүйенуді маңызды деп санадық. Бизнестің құндылығы оның инфрақұрылымы күшті болғанда артады деп сенеміз. Біз нарықтың күнделікті сұраныстарын танитын және біздің операцияларымызды жаңартуда және инновацияда қолдайтын білімді әрі шығармашыл команданы құрдық.',
    'management.philosophy.description2': 'Біздің жетістіктеріміз – төмендегі тәжірибелі мамандар басқаратын кәсіби команда күш-жігерінің нәтижесі:',
    'management.team.chairman.name': 'Татиев Мұрат Петрович',
    'management.team.chairman.position': 'Басқарма төрағасы',
    'management.team.chairman.description': 'Татиев мырза екі жоғары білімге ие, оның ішінде "Қаржы және несие" мамандығы бойынша экономика саласында. 30 жылдық жоғары әкімшілік тәжірибесі бар. Компания құрылғаннан бері стратегиялық жоспарлау, ұйымдастыру және кадрлық басқару жауапкершілігін өз мойнына алды.',
    'management.team.general_director.name': 'Саха Субхасис',
    'management.team.general_director.position': 'Бас директор',
    'management.team.general_director.description': 'Саха мырзаның қонақүй индустриясында Үндістан мен Қазақстанның әртүрлі аймақтарында 25 жылдық тәжірибесі бар. 2002 жылы Ritm Oil ЖК құрылуының алғашқы кезеңінде Бас менеджер болып кірді, барлық нысандардың жұмысын қадағалап, болашақ қонақүйлердің дамуына маңызды үлес қосты. 2010 жылы Бас директор және құрылтайшы ретінде қызметке қабылданды. Ол Үндістанның беделді институттарының бірі - Бангалордағы IHM-де Қонақүй басқармасы бойынша жоғары білім алған.',
    'management.team.operations_manager.name': 'Рой Басаб',
    'management.team.operations_manager.position': 'Операциялар және маркетинг бойынша Бас менеджер',
    'management.team.operations_manager.description': 'Рой мырза, PhD, Әзірбайжан институтында магистр дәрежесін алған. ТМД елдерінде маркетинг саласында үлкен тәжірибесі бар және ТМД-ның әртүрлі аймақтарында жұмыс істеген. 2010 жылдан бері Ritm Oil ЖК-мен жұмыс істеп келеді және ірі мұнай компаниялары мен халықаралық құрылыстық компаниялармен тікелей байланыста компанияны дамытуға белсенді қатысуда.',
    'management.team.hr_director.name': 'Елизарова Ольга Владимировна',
    'management.team.hr_director.position': 'Қызметкерлер жөніндегі директор',
    'management.team.hr_director.description': 'Елизарова ханым, экономика және заң саласындағы академиялық білімі бар, компания құрылғалы бері HR директоры ретінде жұмыс істейді. Қызметкерлер мен әкімшілік жұмысты ұйымдастыруға жауапты.',
    'management.team.finance_director.name': 'Ғабдуллин Нұрлан Иманғазиевич',
    'management.team.finance_director.position': 'Қаржы директоры',
    'management.team.finance_director.description': 'Ғабдуллин мырза Ritm тобының қаржы, қосылу және иемдену, сатып алу және заңдық қызметтерін бақылайды. Ritm тобында 14 жылдан астам қаржы саласында түрлі қызметтер атқарып келеді. Қаржылық жауапкершілік жөніндегі ерекше түсінігі бар. Банктермен және "Даму" мемлекеттік қаржыландыру институтымен барлық келіссөздерді жүргізеді. Экономика ғылымдарының докторы.',
    'management.team.chief_accountant.name': 'Қалимукашева Тамара Ермековна',
    'management.team.chief_accountant.position': 'Бас бухгалтер',
    'management.team.chief_accountant.description': 'Қалимукашева ханым 2003 жылдан бері кәсіпорынның бас бухгалтері болып жұмыс істейді. Оның басқаруымен компанияда 1С платформасында автоматтандырылған есеп және салық есептері енгізілді. Тиімді бухгалтерлік саясатты құру кәсіпорынның қаржылық қызметін табысты жүргізуге мүмкіндік берді.',
    'management.certifications.title': 'Халықаралық стандарттар',
    'management.certifications.description': 'Ritm Oil компаниясының басқармасы халықаралық стандарттарға сәйкес келеді, бұл куәліктермен расталады:',

    // Assets page
    'assets.title': 'Материалдық емес активтер',
    'assets.subtitle': 'Біздің құнды лицензияларымыз, сертификаттарымыз және сенімді серіктестіктеріміз',
    'assets.licenses.title': 'Лицензиялар мен рұқсаттар',
    'assets.licenses.description': '"Ritm Oil" компаниясы негізгі құралдармен қатар қонақүй бизнесін жүзеге асыруға қажетті барлық лицензияларға, шетелдік мамандарға арналған квоталар мен рұқсаттарға ие және Сауда-өнеркәсіп палатасында (CCI) тіркелген "Tengri" тауар белгісінің тіркеу куәлігі бар.',
    'assets.licenses.business.title': 'Қонақүй бизнесі лицензиялары',
    'assets.licenses.business.description': 'Қонақүй қызметін жүзеге асыруға қажетті барлық рұқсаттар',
    'assets.licenses.trademark.title': 'Тауар белгілерін тіркеу',
    'assets.licenses.trademark.description': '"Tengri" тауар белгісі',
    'assets.insurance.title': 'Сақтандыру қамтамасы',
    'assets.insurance.description': 'Біздің барлық жылжымайтын мүліктеріміз Қазақстандағы сақтандыру нарығындағы көшбасшы "Евразия сақтандыру" компаниясының сақтандыру полистерімен қамтылған.',
    'assets.clients.title': 'Тұрақты клиенттер портфелі',
    'assets.clients.description': 'Материалдық емес ең маңызды активтердің бірі — тұрақты, үнемі өсіп келе жатқан клиенттер базасының болуы, оның ішінде әлемдегі ең ірі компаниялар:',
    'assets.clients.list': 'NCOC, Parker Drilling, Saipem, Ersai, Sicim S.p.A., Wagenborg, FMC, Petroleum Facilities Е&C Limited, Weatherford, Baker Hughes, Bolashak Atyrau, Fircroft Engineering, Bonatti, Kaz Story Service, PSN KazStroy, Punj Lloyd, KCA-Deutag, Worley Parsons, Corporation JGС-Marubeni, ССС, Ligabue Central Asia, Bateman, Kentech',
    'assets.clients.footer': 'және басқалары.',
    'assets.financial.title': 'Қаржылық сенім',
    'assets.financial.description': 'Біз барлық жобаларымызды қаржыландырған және біздің қарқынды дамуымызды қолдаған инвесторлар мен банктердің лайықты сеніміне мақтанамыз.',

    // Hotel page
    'hotel.title': 'Қонақүй бизнесі',
    'hotel.subtitle': 'Атырау орталығындағы премиум деңгейдегі тұру қызметтері',
    'hotel.tengri.title': 'Tengri қонақүйі',
    'hotel.tengri.location': 'Атырау қаласының орталығында орналасқан',
    'hotel.tengri.description_1': 'Қонақүй Атырау қаласының орталығында орналасқан. Мұнда 60 бөлме бар, оның 15-і ас үйі бар пәтерлер, 45-і стандартты бөлмелер. Әр бөлмеде телекоммуникация және интернет байланысы, кондиционер және көптілді спутниктік телевизиялық жүйе орнатылған.',
    'hotel.tengri.description_2': 'Біздің қонақтар әсіресе Италия мен Үндістаннан келген аспаздар басқаратын мейрамхананы жоғары бағалайды. Қонақүйдегі бар қонақтарға әріптестер мен достарымен демалып, кездесулер өткізуге мүмкіндік береді. Лаундж-бар кең экранды проекциялық жүйемен жабдықталған, мұнда қонақтар әртүрлі спорттық іс-шараларды тамашалай алады.',
    'hotel.tengri.description_3': 'Бардың қосымша тартымдылығы — әр сәрсенбі және сенбі күндері өтетін жергілікті Атырау қаласының ең танымал музыкалық топтарының бірі ұйымдастыратын тірі музыка.',
    'hotel.amenities.rooms': '60 бөлме',
    'hotel.amenities.rooms_desc': '15 ас үйі бар пәтерлер, 45 стандартты бөлме',
    'hotel.amenities.connectivity': 'Қазіргі заманғы байланыс',
    'hotel.amenities.connectivity_desc': 'Әр бөлмеде телекоммуникация және интернет байланысы',
    'hotel.amenities.cuisine': 'Итальян және Үндістан асханасы',
    'hotel.amenities.cuisine_desc': 'Италия мен Үндістаннан келген аспаздар басқаратын мейрамхана',
    'hotel.amenities.entertainment': 'Тірі ойын-сауық',
    'hotel.amenities.entertainment_desc': 'Сәрсенбі және сенбі күндері тірі музыка',
    'hotel.booking.title': 'Тұруды брондаңыз',
    'hotel.booking.description': 'Tengri қонақүйінде жайлылық пен қонақжайлылықты сезініңіз',
    'hotel.booking.button': 'Қазір брондау',

    // Catering page
    'catering.title': 'Кейтеринг және лагерьді басқару',
    'catering.subtitle': 'Кең ауқымды тамақтандыру қызметтері мен лагерьді басқару шешімдері',
    'catering.services.title': 'Біздің кейтеринг қызметтеріміз',
    'catering.services.subtitle': 'Қазақстан бойынша ерекше тамақтандыру қызметтері мен лагерьді басқару қызметтерін ұсыну',
    'catering.description_1': '"Ritm Camp" және "Punj Lloyd" лагерьлерін басқарумен қатар, біз 2011 жылға дейін "Consolidate Contractors Company" (CCC) компаниясына тәулігіне 1800 адамға тамақтандыру, техникалық қызмет көрсету және тазалық қызметтерін толық көлемде ұсындық.',
    'catering.description_2': 'Тамақтандыру қызметінің жоғары стандарты бізге 2013 жылы Атыраудағы "Agip Оқу Орталығында" кейтеринг және тазалық қызметтерін ұсыну бойынша Agip KCO тендерін жеңуге көмектесті.',
    'catering.description_3': 'Біз кез келген клиенттің арнайы іс-шараларында ашық аспан астындағы кейтеринг қызметтерін ұйымдастырып, ұсынамыз.',
    'catering.services.camp_management': 'Лагерьді басқару',
    'catering.services.camp_management_desc': 'Кейтеринг, техникалық қызмет көрсету және тазалық қызметтерін қоса алғанда, лагерьді толық басқару',
    'catering.services.high_capacity': 'Жоғары сыйымдылық',
    'catering.services.high_capacity_desc': 'Әртүрлі жерлерде тәулігіне 1800 адамға дейін қызмет көрсету',
    'catering.services.quality_food': 'Сапалы тамақтандыру қызметі',
    'catering.services.quality_food_desc': 'Ірі тендерді жеңуге көмектескен жоғары стандарттағы тамақтандыру қызметі',
    'catering.services.event_catering': 'Іс-шараларға кейтеринг',
    'catering.services.event_catering_desc': 'Арнайы іс-шараларға ашық аспан астындағы кейтеринг қызметтерін ұйымдастыру және ұсыну',
    'catering.achievements.title': 'Негізгі жетістіктер',
    'catering.achievements.people_served': 'Тәулігіне қызмет көрсетілген адамдар саны',
    'catering.achievements.agip_tender': 'Agip KCO тендерін жеңу',
    'catering.achievements.years_experience': 'Жылдар бойы тәжірибе',

    //Transport page
    'transport.title': 'Тасымалдау және логистика',
    'transport.subtitle': 'Мұнай-газ саласы үшін кешенді логистикалық шешімдер',
    'transport.services.title': 'Тасымалдау және логистикалық қызметтер',
    'transport.services.subtitle': 'Бүгінгі талапшыл нарыққа арналған заманауи логистикалық шешімдер',
    'transport.full_range': 'Толық логистикалық қызметтер',
    'transport.full_range_desc': 'Жүк ағындарын және жеткізу тізбегін басқаруға арналған толық логистикалық қызметтер',
    'transport.just_in_time': 'Дәл уақытында жеткізу',
    'transport.just_in_time_desc': 'Тұтынушылар сұранысы мен өндіріс қажеттіліктеріне сәйкес тиімді жеткізу кестелері',
    'transport.packing_moving': 'Орау және көшіру',
    'transport.packing_moving_desc': 'Тұрмыстық және корпоративтік заттарды кәсіби түрде орау және көшіру қызметтері',
    'transport.city_transport': 'Қалаішілік және қалааралық тасымалдау',
    'transport.city_transport_desc': 'Қалалар ішінде және аймақтар арасында сенімді тасымалдау қызметтері',
    'transport.main_content.overview': 'Ritm Oil ЖШС мұнай-газ саласына маманданған, жүк ағындарын және жеткізу тізбегін басқаруға арналған кешенді логистикалық қызметтер ұсынады.',
    'transport.main_content.supply_chain': 'Бүгінгі қарқынды нарықта біз өзгеретін клиент талаптары мен өндіріс кестелеріне икемделетін икемді жеткізу шешімдерін ұсынамыз. Біздің тиімді тасымалдау модельдері шығындарды оңтайландыра отырып, қалаішілік және қалааралық операцияларда жоғары қызмет сапасын қамтамасыз етеді.',
    'transport.packing_moving.description': 'Біз тұрмыстық және корпоративтік клиенттерге арналған арнайы орау және көшіру қызметтерін ұсынамыз, нақты талаптарыңызға бейімделген шешімдермен. Біздің тиімді процесс күрделі көшу жұмыстарын оңай әрі кедергісіз етеді.',
    'transport.packing_moving.customer_service': 'Тамаша клиенттерге қызмет көрсетуге деген біздің міндетіміз бізді ерекшелендіреді, әрбір клиентке жеке көңіл бөліп, көшу процесін жеңіл әрі ұтымды етеді.',

    // Management agreement page
    'mgmtagree.title': 'Басқару келісімшарты',
    'mgmtagree.subtitle': 'Меншік иелері үшін кәсіби қонақүйді басқару қызметтері',
    'mgmtagree.services.title': 'Қонақүйді басқару қызметтері',
    'mgmtagree.services.subtitle': 'Қонақүй мүліктерін басқаруға арналған кешенді шешімдер',
    'mgmtagree.description_1': 'Біздің басқару келісімшарттарымыз үшінші тараптың қонақүй иелеріне толық басқару қызметтерін ұсынады. Біз қонақүйдің жалпы кірісінен пайыз және қонақүй бөлімшесінің операциялық пайдасына байланысты басқа басқару төлемдерін аламыз.',
    'mgmtagree.description_2': 'Сонымен қатар, біз сатылымдар мен маркетинг үшін төлем аламыз, ол сатылған бөлмелер санына негізделген, бұл біздің мүдделерімізді сіздің мүлкіңіздің табысына сәйкестендіреді.',
    'mgmtagree.description_3': 'Келісімшарттар әдетте 5-10 жыл немесе одан ұзақ мерзімге жасалады, бірақ ол орналасқан жері мен клиенттік/мүлік түріне байланысты.',
    'mgmtagree.features.total_services': 'Толық басқару қызметтері',
    'mgmtagree.features.total_services_desc': 'Үшінші тараптың қонақүй иелеріне арналған толық басқару қызметтері',
    'mgmtagree.features.performance_fees': 'Нәтижеге негізделген төлемдер',
    'mgmtagree.features.performance_fees_desc': 'Қонақүйдің жалпы кірісі мен пайдасына негізделген төлемдер',
    'mgmtagree.features.long_term': 'Ұзақ мерзімді келісімшарттар',
    'mgmtagree.features.long_term_desc': 'Мүлік қажеттілігіне байланысты 5-10 жыл немесе одан ұзақ мерзімді икемді келісімдер',
    'mgmtagree.features.sales_marketing': 'Сату және маркетинг',
    'mgmtagree.features.sales_marketing_desc': 'Сатылған бөлмелер саны мен маркетинг нәтижесіне негізделген қосымша төлемдер',
    'mgmtagree.fee_structure.title': 'Төлем құрылымы',
    'mgmtagree.fee_structure.management_fee': 'Басқару ақысы',
    'mgmtagree.fee_structure.management_fee_desc': 'Қонақүйдің жалпы кірісінен пайыз',
    'mgmtagree.fee_structure.performance_fee': 'Нәтижеге негізделген ақы',
    'mgmtagree.fee_structure.performance_fee_desc': 'Қонақүй пайдасынан пайыз',
    'mgmtagree.fee_structure.marketing_fee': 'Маркетинг ақысы',
    'mgmtagree.fee_structure.marketing_fee_desc': 'Сатылған бөлмелер санына негізделген',

    //Franchise page
    'franchise.title': 'Франчайзинг келісімшарттары',
    'franchise.subtitle': 'Халықаралық брендтердің франчайзинг мүмкіндіктері мен қолдауы',
    'franchise.services.title': 'Франчайзинг қызметтері',
    'franchise.services.subtitle': 'Қонақүй иелерін халықаралық бренд мүмкіндіктерімен байланыстыру',
    'franchise.description_1': 'Біздің франчайзинг келісімшарттарымызда біз мүлікті басқарған тәжірибесі бар үшінші тарап операторы немесе мүлік иесін бағалаймыз. Осы келісімшарттар бойынша біз қонақүйді иемденбейміз, жалға алмаймыз және басқармаймыз.',
    'franchise.description_2': 'Табысымыз брендтік роялти немесе лицензиялық төлемдерден келеді, ол қонақүйден түскен бөлме табысының пайызына негізделген. Сонымен қатар, біз маркетинг төлемдерін және броньдаулар санына байланысты төлемдерді жинаймыз.',
    'franchise.description_3': 'Біз қонақүйдің үшінші тарап иелеріне Holiday Inn, Ramada, Park Inn, Accor сияқты халықаралық брендтердің франшизаларын алуға көмектесе аламыз.',
    'franchise.features.brand_assistance': 'Бренд қолдауы',
    'franchise.features.brand_assistance_desc': 'Үшінші тарап иелеріне халықаралық бренд франшизаларын алуға көмек көрсету',
    'franchise.features.qualified_staff': 'Білікті персонал',
    'franchise.features.qualified_staff_desc': 'Тәжірибелі және білікті персоналмен операторларды бағалау',
    'franchise.features.marketing_support': 'Маркетингтік қолдау',
    'franchise.features.marketing_support_desc': 'Броньдау жүйесіне қолжетімділік және маркетинг білімі',
    'franchise.features.brand_standards': 'Бренд стандарттары',
    'franchise.features.brand_standards_desc': 'Белгіленген бренд стандарттары мен имиджін сақтау',
    'franchise.partner_brands.title': 'Серіктес брендтер',
    'franchise.brand_standards.title': 'Бренд стандарттары',
    'franchise.brand_standards.description': 'Бренд имиджі мен құндылығын сақтау үшін франчайзи белгіленген бренд стандарттарын орындауға міндетті. Франчайзи броньдау жүйесіне қол жеткізеді және қонақүйді басқаруға арналған маркетингтік қолдау мен басқа да білімдермен қамтамасыз етіледі.',
    'franchise.contract.title': 'Келісімшарт мерзімі',
    'franchise.contract.description': 'Біздің франчайзинг келісімшарттарымыздың мерзімі 5-10 жыл аралығында болып, меншік иелері үшін тұрақтылық пен ұзақ мерзімді серіктестік мүмкіндіктерін қамтамасыз етеді.',
    
    // Clients page
    'clients.title': 'Біздің клиенттер',
    'clients.subtitle': 'Мұнай және газ саласындағы жетекші компаниялардың сенімі',
    'clients.description_1': "Біз әлемдегі ең беделді энергетика саласындағы компанияларға қызмет көрсетуден мақтанамыз, Қазақстан бойынша сенімді және кәсіби қызметтер ұсынамыз. Клиенттеріміздің кең портфолиосы біздің жоғары сапаға берілгендігімізді және халықаралық корпорациялардың талаптарына сай болуымызды көрсетеді.",
    'clients.description_2': "Ірі мұнай компанияларынан бастап инженерлік мердігерлерге дейін, біздің әртүрлі клиенттеріміз энергетика саласының барлық сегменттерін қамтиды, бұл біздің қызметтеріміздің ауқымдылығын және табысты жобаларды жүзеге асырудағы тәжірибемізді айғақтайды.",
    'clients.partners.title': 'Біздің бағалы серіктестеріміз',
    'clients.partnership.title': 'Тұрақты серіктестіктерді құру',
    'clients.partnership.description': "Екі онжылдықтан астам уақыт бойы біз клиенттерімізбен берік қарым-қатынасты ұстап келеміз, үздік қызмет сапасын тұрақты түрде ұсынып. Сапаға берілгендігіміз Қазақстандағы энергетика секторындағы ірі халықаралық компаниялардың таңдаулы серіктесіне айналдырды.",
    'clients.stats.clients': 'Ірі клиенттер',
    'clients.stats.years': 'Серіктестік жылдары',
    'clients.stats.satisfaction': 'Клиенттердің қанағаттануы',

    //Contacts page
    'contacts.hero.title': 'Байланыс',
    'contacts.hero.description': 'Бизнестегі қажеттіліктеріңізді талқылау және қалай көмектесе алатынымызды білу үшін командамызбен байланысыңыз',
    'contacts.form.title': 'Хабарлама жіберу',
    'contacts.form.name_label': 'Толық аты-жөніңіз',
    'contacts.form.name_placeholder': 'Толық атыңызды енгізіңіз',
    'contacts.form.email_label': 'Электрондық пошта',
    'contacts.form.email_placeholder': 'Электрондық поштаңызды енгізіңіз',
    'contacts.form.subject_label': 'Тақырыбы',
    'contacts.form.subject_placeholder': 'Хабарлама тақырыбын енгізіңіз',
    'contacts.form.message_label': 'Хабарлама',
    'contacts.form.message_placeholder': 'Хабарламаңызды енгізіңіз',
    'contacts.form.robot_label': 'Мен робот емеспін',
    'contacts.form.robot_error': 'Өтінеміз, робот еместігіңізді растаңыз',
    'contacts.form.success_message': 'Хабарлама сәтті жіберілді! Жақында сізге жауап береміз.',
    'contacts.form.submit_button': 'Хабарлама жіберу',
    'contacts.info.title': 'Байланыста болыңыз',
    'contacts.info.main_office': 'Бас офис',
    'contacts.info.address_label': 'Мекенжай',
    'contacts.info.phone_label': 'Телефон',
    'contacts.info.email_label': 'Электрондық пошта',
    'contacts.info.tel_fax': 'Тел/Факс',
    'contacts.info.mobile': 'Моб',
    'contacts.info.skype': 'Skype',
    'contacts.info.email': 'Email',
    'contacts.departments.title': 'Бөлімшелердің байланыс деректері',
    // Department contact information
    'contacts.departments.head_office.name': 'Ritm Oil ЖШС',
    'contacts.departments.head_office.position': 'Бас офис',
    'contacts.departments.head_office.department': 'Әкімшілік',
    'contacts.departments.head_office.address': 'Дружба к-сі, 1а, 060007 Атырау, Қазақстан Республикасы',

    'contacts.departments.hotel.name': 'Қонақүй және лагерь',
    'contacts.departments.hotel.position': 'Теңгри қонақүйі',
    'contacts.departments.hotel.department': 'Қонақүй және лагерь',
    'contacts.departments.hotel.address': 'Абай к-сі, 23, 060007 Атырау, Қазақстан Республикасы',

    'contacts.departments.franchise.name': 'Франчайзинг және басқару',
    'contacts.departments.franchise.position': 'Франчайзинг және басқару',
    'contacts.departments.franchise.department': 'Франчайзинг және басқару',
    'contacts.departments.franchise.address': 'Дружба к-сі, 1а, 060007 Атырау, Қазақстан Республикасы',

    'contacts.departments.vacancy.name': 'Бос жұмыс орындары',
    'contacts.departments.vacancy.position': 'Адам ресурстары бөлімі',
    'contacts.departments.vacancy.department': 'Бос жұмыс орындары',
    'contacts.departments.vacancy.address': 'Дружба к-сі, 1а, 060007 Атырау, Қазақстан Республикасы',

  }
};
